# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'InvestmentsFintech' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'R.swift'
  pod 'SwiftLint'
  pod 'AuthModule', :git => 'https://github.com/MaxiJunkie/AuthModuleLibrary.git', :branch => 'dev'
      
end
