# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'investmentsFintech' do
  use_frameworks!
	
	pod 'R.swift'
  
target 'investmentsFintechTests' do
    inherit! :search_paths

  end

end
